# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2025-04-25 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='imagenes_mascota'),
        ),
    ]
