# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2025-04-25 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(error_messages={'required': 'error: required username'}, max_length=50),
        ),
    ]
